// Hardcoded fake-name pools. Combine a random first + last to make variety.
// Intentionally no dependency on @faker-js/faker — keeps the bundle small.

export const FIRST_NAMES: readonly string[] = [
  'Aiden', 'Ava', 'Alice', 'Arjun', 'Amelia', 'Aaron', 'Adriana', 'Andre',
  'Benjamin', 'Bella', 'Beatrice', 'Bryce', 'Brianna', 'Bart', 'Blair',
  'Caleb', 'Chloe', 'Carmen', 'Cassie', 'Cyrus', 'Charlotte', 'Clark', 'Colin',
  'Diana', 'Declan', 'Dante', 'Daphne', 'Derek', 'Daria', 'Dominic',
  'Ethan', 'Eva', 'Elena', 'Eli', 'Ezra', 'Esme', 'Elliot', 'Evelyn',
  'Felix', 'Fiona', 'Frances', 'Finn', 'Freya', 'Fatima', 'Felipe',
  'Grace', 'Gabriel', 'Giselle', 'Grant', 'Gwen', 'George', 'Greta',
  'Hazel', 'Hugo', 'Hassan', 'Helena', 'Hunter', 'Harper', 'Holly',
  'Isla', 'Ivan', 'Ines', 'Isaiah', 'Ivy', 'Indira', 'Ira',
  'Jade', 'Jasper', 'Julia', 'Jonah', 'Jun', 'Josephine', 'Jamal', 'Joanna',
  'Kai', 'Kira', 'Keanu', 'Kendra', 'Kieran', 'Kate', 'Karim',
  'Luna', 'Leo', 'Liam', 'Lila', 'Luis', 'Lena', 'Lucas', 'Lorenzo',
  'Maya', 'Mason', 'Mira', 'Marcus', 'Mei', 'Mateo', 'Molly', 'Marco',
  'Nora', 'Niko', 'Nadia', 'Nathaniel', 'Nina', 'Noah', 'Neil',
  'Olivia', 'Omar', 'Otto', 'Opal', 'Oscar', 'Oliver', 'Ophelia',
  'Priya', 'Pablo', 'Penelope', 'Phoebe', 'Percy', 'Paloma', 'Peter',
  'Quinn', 'Quincy',
  'Rosa', 'Rafael', 'Ruby', 'Reuben', 'Raven', 'Roman', 'Rita',
  'Sophia', 'Samir', 'Selena', 'Silas', 'Saoirse', 'Sadie', 'Sebastian',
  'Theo', 'Tara', 'Tobias', 'Tessa', 'Trevor', 'Talia', 'Theodore',
  'Ursula', 'Umar',
  'Victor', 'Violet', 'Vera', 'Vincent', 'Valeria',
  'Wyatt', 'Willa', 'Wesley', 'Wren',
  'Xavier', 'Ximena',
  'Yusuf', 'Yara', 'Yael',
  'Zara', 'Zane', 'Zoe', 'Zion',
];

export const LAST_NAMES: readonly string[] = [
  'Abbott', 'Adler', 'Alvarez', 'Anderson', 'Ashford', 'Aoki',
  'Barnes', 'Becker', 'Blake', 'Brennan', 'Bright', 'Brooks', 'Burgess',
  'Caldwell', 'Carter', 'Chandra', 'Cho', 'Cohen', 'Cortez', 'Cruz',
  'Dalton', 'Darwin', 'Davies', 'Delgado', 'Dupont', 'Doyle', 'Duarte',
  'Eaton', 'Elder', 'Ellis', 'Emerson', 'Esparza',
  'Falk', 'Ferrer', 'Finch', 'Flores', 'Forsyth', 'Foster', 'Fuentes',
  'Garber', 'Gomez', 'Graham', 'Greenwood', 'Gupta', 'Guerrero',
  'Hale', 'Hansen', 'Harlow', 'Hayes', 'Higgins', 'Holm', 'Huang',
  'Iverson', 'Ishida', 'Ingram',
  'Jackson', 'Jimenez', 'Jones', 'Jung',
  'Kane', 'Kaur', 'Keller', 'Kennedy', 'Khan', 'Kim', 'Klein', 'Kovac',
  'Larsen', 'Lee', 'Levine', 'Lindquist', 'Lopez', 'Lowell', 'Luna',
  'Maddox', 'Mahoney', 'Marquez', 'Matsuda', 'Mendoza', 'Mercer', 'Moreno', 'Murphy',
  'Nakamura', 'Navarro', 'Nguyen', 'Nichols', 'Nowak',
  'Okafor', 'Oliveira', 'Ortega', 'Osborne', 'Owens',
  'Palmer', 'Park', 'Patel', 'Pena', 'Perez', 'Preston', 'Pullman',
  'Quade', 'Quinn',
  'Ramirez', 'Rask', 'Reeves', 'Rivera', 'Rojas', 'Romero', 'Ross', 'Ruiz',
  'Sanders', 'Santos', 'Sato', 'Schmidt', 'Serrano', 'Singh', 'Soto', 'Stein', 'Sullivan',
  'Takahashi', 'Tan', 'Tate', 'Thornton', 'Torres', 'Trent', 'Tucker',
  'Ueda', 'Underwood',
  'Valdez', 'Vargas', 'Velasquez', 'Vogel', 'Vu',
  'Walker', 'Wang', 'Weaver', 'Webb', 'Whitman', 'Wilson', 'Wright',
  'Xiong', 'Ximenez',
  'Yamada', 'Yates', 'Young', 'Yousef',
  'Zhang', 'Zhao', 'Zimmer', 'Zuniga',
];
